spring:
  profiles: peer2
  application:
    name: discovery-ha
  security:
    user:
      name: admin
      password: 123456
server:
  port: 8762

logging:
  path: logs/log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    hostname: peer2 # 指定当profile
    metadata-map:
      user.name: admin
      user.password: 123456
  client:
    serviceUrl:
      defaultZone: http://admin:123456@peer1:8761/eureka/,http://admin:123567@peer3:8763/eureka/