server:
  port: 8766
spring:
  application:
    name: microservice-consumer-demo # 项目名称尽量用小写

logging:
  path: logs/log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@peer1:8761/eureka/,http://admin:123456@peer2:8762/eureka/,http://admin:123567@peer3:8763/eureka/

  instance:
    preferIpAddress: true